name: Run Deploy

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 14
          npm: latest

      - name: Clean npm cache
        run: npm cache clean --force
        working-directory: frontend

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Build and Deploy
        run: npm run deploy
        working-directory: frontend
